kind: ConfigMap
apiVersion: v1
metadata:
  name: config-map-example-env-var
data:
  sample-key: config/random-path.yaml
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: config-map-example-config-file
data:
  random-path.yaml: |
    logs: info # can be debug, info, error
    secret_key_path: secrets/super-secret-1
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-super
type: Opaque
data:
  super-secret-1: aSBsb3ZlIHpoYW5nIHp1byByYW4=
  super-secret-2: aSBsb3ZlIHdlaWppZQ==
---
apiVersion: v1
kind: Pod
metadata:
  name: "config-map-example"
  labels:
    app: "config-map-example"
spec:
  containers:
  - name: config-map-example
    image: "kirinnee/thp-node:time-v2"
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
    env:
    - name: ENV
      value: DEV
    - name: CONFIG_PATH
      valueFrom:
        configMapKeyRef:
          name: config-map-example-env-var
          key: sample-key
    ports:
    - containerPort:  80
      name:  http
    volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
      - name: secrets
        mountPath: "/secrets"
        readOnly: true
  volumes:
    - name: config
      configMap:
        name: config-map-example-config-file
    - name: secrets
      secret:
        secretName: secret-super
  restartPolicy: Always