apiVersion: v1
kind: Pod
metadata:
  name: time-v1
  labels:
    version: v1
    service: atomi.core.time
    env: dev
  annotations:
    created-by: kirinnee
spec:
  containers:
    - name: api
      image: "kirinnee/thp-node:time-v1"
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 100m
          memory: 200Mi
      env:
        - name: ENV
          value: DEV
        - name: CONFIG_PATH
          value: config.yaml
      ports:
        - containerPort: 3000
          name: http
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: time-v1
  labels:
    version: v1
    service: atomi.core.time
    env: dev
  annotations:
    created-by: kirinnee
spec:
  selector:
    version: v1
    service: atomi.core.time
    env: dev
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: time-v2
  labels:
    version: v2
    service: atomi.core.time
    env: dev
  annotations:
    created-by: kirinnee
spec:
  containers:
    - name: api
      image: "kirinnee/thp-node:time-v2"
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 100m
          memory: 200Mi
      env:
        - name: ENV
          value: DEV
        - name: CONFIG_PATH
          value: config.yaml
      ports:
        - containerPort: 3000
          name: http
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: time-v2
  labels:
    version: v2
    service: atomi.core.time
    env: dev
  annotations:
    created-by: kirinnee
spec:
  selector:
    version: v2
    service: atomi.core.time
    env: dev
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: random-v1
  labels:
    version: v1
    service: atomi.core.random
    env: dev
  annotations:
    created-by: kirinnee
spec:
  containers:
    - name: api
      image: "kirinnee/thp-node:random-v1"
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 100m
          memory: 200Mi
      env:
        - name: ENV
          value: DEV
        - name: CONFIG_PATH
          value: config.yaml
      ports:
        - containerPort: 3000
          name: http
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: random-v1
  labels:
    version: v1
    service: atomi.core.random
    env: dev
  annotations:
    created-by: kirinnee
spec:
  selector:
    version: v1
    service: atomi.core.random
    env: dev
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: random-v2
  labels:
    version: v2
    service: atomi.core.random
    env: dev
  annotations:
    created-by: kirinnee
spec:
  containers:
    - name: api
      image: "kirinnee/thp-node:random-v2"
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 100m
          memory: 200Mi
      env:
        - name: ENV
          value: DEV
        - name: CONFIG_PATH
          value: config.yaml
      ports:
        - containerPort: 3000
          name: http
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: random-v2
  labels:
    version: v2
    service: atomi.core.random
    env: dev
  annotations:
    created-by: kirinnee
spec:
  selector:
    version: v2
    service: atomi.core.random
    env: dev
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: time-v1-prod
  labels:
    version: v1
    service: atomi.core.time
    env: prod
  annotations:
    created-by: kirinnee
spec:
  containers:
    - name: api
      image: "kirinnee/thp-node:time-v1"
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 100m
          memory: 200Mi
      env:
        - name: ENV
          value: PROD
        - name: CONFIG_PATH
          value: config.yaml
      ports:
        - containerPort: 3000
          name: http
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: time-v1-prod
  labels:
    version: v1
    service: atomi.core.time
    env: prod
  annotations:
    created-by: kirinnee
spec:
  selector:
    version: v1
    service: atomi.core.time
    env: prod
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: time-v2-prod
  labels:
    version: v2
    service: atomi.core.time
    env: prod
  annotations:
    created-by: kirinnee
spec:
  containers:
    - name: api
      image: "kirinnee/thp-node:time-v2"
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 100m
          memory: 200Mi
      env:
        - name: ENV
          value: PROD
        - name: CONFIG_PATH
          value: config.yaml
      ports:
        - containerPort: 3000
          name: http
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: time-v2-prod
  labels:
    version: v2
    service: atomi.core.time
    env: prod
  annotations:
    created-by: kirinnee
spec:
  selector:
    version: v2
    service: atomi.core.time
    env: prod
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: random-v1-prod
  labels:
    version: v1
    service: atomi.core.random
    env: prod
  annotations:
    created-by: kirinnee
spec:
  containers:
    - name: api
      image: "kirinnee/thp-node:random-v1"
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 100m
          memory: 200Mi
      env:
        - name: ENV
          value: PROD
        - name: CONFIG_PATH
          value: config.yaml
      ports:
        - containerPort: 3000
          name: http
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: random-v1-prod
  labels:
    version: v1
    service: atomi.core.random
    env: prod
  annotations:
    created-by: kirinnee
spec:
  selector:
    version: v1
    service: atomi.core.random
    env: prod
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: random-v2-prod
  labels:
    version: v2
    service: atomi.core.random
    env: prod
  annotations:
    created-by: kirinnee
spec:
  containers:
    - name: api
      image: "kirinnee/thp-node:random-v2"
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 100m
          memory: 200Mi
      env:
        - name: ENV
          value: PROD
        - name: CONFIG_PATH
          value: config.yaml
      ports:
        - containerPort: 3000
          name: http
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: random-v2-prod
  labels:
    version: v2
    service: atomi.core.random
    env: prod
  annotations:
    created-by: kirinnee
spec:
  selector:
    version: v2
    service: atomi.core.random
    env: prod
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
---

