logs: debug # can be debug, info, error
secret_key_path: secret_file.txt
random_settings:
  int:
    start: -1000000000
    end: 1000000000
  float:
    start: -1000000000
    end: 1000000000
  word:
    number: 3
    format: kebab # "kebab" | "camel" | "sentence" | "lower" | "title"
